### ISSUE TITLE
amplitude cut-out

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spikemetrics#1]
@colehurwitz you can use the amplitude cutout by computing the amplitude of single waveforms

**Comment by colehurwitz** [comment]
Ok, so it can be amplitude scales or just amplitudes?

**Comment by alejoe91** [comment]
we can decide. If we want scales we can just divide the waveform amp by the average template amp

**Comment by colehurwitz** [comment]
Can you possibly implement the amplitude extraction? I am planning on working on connecting validation and metrics next (although my summer school starts today). If you do have time to work on it, the validation branch is the right place to implement it.

**Comment by alejoe91** [comment]
I think it should go in postprocessing: `get_unit_amplitudes`. Did you make a PR for spiketoolkit?

**Comment by alejoe91** [comment]
In my mind the validation should call posptrocessing functions for preparation and then spikemetrics to extract the units. I'll give you my feedback once you make a PR :)

**Comment by colehurwitz** [comment]
No, the validation branch isn’t quite ready for a PR. I made changes in post processing and I will start changing validation as well.

**Comment by alejoe91** [comment]
I think it's better if you make a WIP PR, so we can comment straightaway one the approach! I won't have time to work on it though before a few weeks. So we can leave this open

**Comment by colehurwitz** [comment]
Yes. Validation will use postprocessing extensively. Basically, I plan to have each metric be able to be returned separately and also all the metrics returned together in a panda data frame (as josh did).

**Comment by colehurwitz** [comment]
I can make a WIP PR today
