### ISSUE TITLE
mahalanobis metrics: possible error

### ISSUE THREAD

**Issue by DanBenHa** [SpikeInterface/spikemetrics#10]
I have two questions regarding the `mahalanobis_metrics` function.

1. Why is `mahalanobis_self` computed but never used? https://github.com/SpikeInterface/spikemetrics/blob/7c5bd7205c39a6feca4aa05c53ffbc075ecf040e/spikemetrics/metrics.py#L630
2. Shouldn't the L-ratio be L normalised to the number of _cluster spikes_? Here, it is normalised to the number of **non-cluster** spikes: https://github.com/SpikeInterface/spikemetrics/blob/7c5bd7205c39a6feca4aa05c53ffbc075ecf040e/spikemetrics/metrics.py#L638
See equation 4 in Schmitzer-Torbert et al. 2005.

**Comment by alejoe91** [comment]
Hey @DanBenHa 

Sorry for the super late response! I think this was fixed here: https://github.com/SpikeInterface/spikemetrics/commit/fd6798a77b660cc3b39eac2ff4cf09de8788259c

Feel free to reopen the issue or make a PR if you find other possible mistakes!
