### ISSUE TITLE
Mistake in L-ratio calculation

### ISSUE THREAD

**Issue by jsiegle** [SpikeInterface/spikemetrics#21]
@bartulem opened [an issue in the ecephys_spike_sorting repo](https://github.com/AllenInstitute/ecephys_spike_sorting/issues/52) noting that the normalization factor used to calculate L-ratio is incorrect. I checked the original reference, and this is indeed the case.

It's an easy fix (change `mahalanobis_other` to `mahalanobis_self` on line 683 of `metrics.py`), but what's the appropriate way to document the change?

**Comment by alejoe91** [comment]
Hi @jsiegle 

Can you make a PR? We can make a new release and use the github release page to log the changes. What do you think?

**Comment by alejoe91** [comment]
@jsiegle fixed here https://github.com/SpikeInterface/spikemetrics/pull/23 and documented here: https://github.com/SpikeInterface/spikemetrics/releases

**Comment by jsiegle** [comment]
Awesome, thanks!
