### ISSUE TITLE
PC-metrics error  with curated output of KS2 

### ISSUE THREAD

**Issue by ratliffj** [SpikeInterface/spikemetrics#22]
Hi

I am having some trouble analyzing my KS2 output after manual curation. Running the metrics on my data fails during the PC metrics calculation with an indexing error (traceback below). I am wondering if this is related to the issue on the ECEphys Project: https://github.com/AllenInstitute/ecephys_spike_sorting/issues/45.

Also, I am using a non-neuropixel probe. I'm not sure if this has something to do with it also.
 
IndexError                                Traceback (most recent call last)
<ipython-input-102-1632b7b1d421> in <module>
     20                          }
     21 
---> 22 sm.metrics.calculate_metrics(spike_times = ksData[0], spike_clusters = ksData[1], amplitudes = ksData[3], 
     23                              pc_features = ksData[8], pc_feature_ind = ksData[9], cluster_ids = ksData[6],
     24                              duration =  16669,

C:\ProgramData\Anaconda3\lib\site-packages\spikemetrics\metrics.py in calculate_metrics(spike_times, spike_clusters, amplitudes, pc_features, pc_feature_ind, params, duration, cluster_ids, epochs, seed, verbose)
     86 
     87         print("Calculating PC-based metrics")
---> 88         isolation_distance, l_ratio, d_prime, nn_hit_rate, nn_miss_rate = calculate_pc_metrics(spike_clusters[in_epoch],
     89                                                                                                total_units,
     90                                                                                                pc_features[in_epoch, :,

C:\ProgramData\Anaconda3\lib\site-packages\spikemetrics\metrics.py in calculate_pc_metrics(spike_clusters, total_units, pc_features, pc_feature_ind, num_channels_to_compare, max_spikes_for_cluster, spikes_for_nn, n_neighbors, min_num_pcs, metric_names, seed, spike_cluster_subset, verbose)
    283         for_unit = np.squeeze(spike_clusters == cluster_id)
    284         pc_max = np.argmax(np.mean(pc_features[for_unit, 0, :], 0))
--> 285         peak_channels[cluster_id] = pc_feature_ind[cluster_id, pc_max]
    286 
    287     for idx, cluster_id in enumerate(cluster_ids):

IndexError: index 1232 is out of bounds for axis 0 with size 1232

**Comment by alejoe91** [comment]
@ratliffj this is now fixed! The problem was that in loading `Phy` data there was an extra dimension in the amplitudes (num_spikes, 1). It has been fixed with this commit: https://github.com/SpikeInterface/spikeextractors/commit/f292d1886dab6f9cc25615f408f1e0aa3afe1573
