### ISSUE TITLE
PC metrics: index issues

### ISSUE THREAD

**Issue by khl02007** [SpikeInterface/spikemetrics#24]
Noticed a number of issues with `calculate_pc_metrics` in `metrics.py`:
1. At numerous places the script confuses between the *index* and *ID* of a unit - in principle there is no relationship between the two (e.g. the first unit, who is given index 0, may be given ID 47 for whatever reason). This might explain https://github.com/SpikeInterface/spikemetrics/issues/22#issue-677837745
2. The script tries to identify units that were detected on the same set of electrodes prior to computing the metrics. To do so it currently uses channels around the peak channel (something like `np.arange(peak_channel-half_spread:peak_channel+half_spread)`). This is obviously problematic:
  * What if peak_channel-half_spread is negative? Or peak_channel+half_spread is greater than max index of channels?
  * What if the channels that were passed in are not even in numerical in progression? In many electrode arrays there is no relationship between channel numbering and geometric location, e.g. channel 1 is not necessarily next to channel 2. So the user may pass in a set of channels whose indices don't have a natural ordering and yet are geometrically close. Note that Neuropixels 1.0 does have such a relationship between channel numbering and geometric location (and I understand this script was originally written to process Neuropixels recordings), but this is a special case and the script shouldn't assume this.

Submitted a [pull request](https://github.com/SpikeInterface/spikemetrics/pull/25#issue-538646355) that addresses these issues. I fixed issue 1 by being more consistent, and 2 by asking for the 2D coordinates of the channels (this can be gotten from the spikeextractors RecordingExtractor, for example) and computing the k nearest channels to the peak channel of the target unit.

I tested this on my own data, but can someone test it on other datasets?

**Comment by alejoe91** [comment]
Thank you so much Kyu for finding these issues and for the PR. I'll review it later today but your solutions sound good.

**Comment by khl02007** [comment]
Thanks. By the way, if we make this change we may also need to change some of the functions in `spiketoolkit` package that call `calculate_pc_metrics`, such as [quality_metrics.py](https://github.com/SpikeInterface/spiketoolkit/blob/master/spiketoolkit/validation/quality_metrics.py) and [nearest_neighbor.py](https://github.com/SpikeInterface/spiketoolkit/blob/master/spiketoolkit/validation/quality_metric_classes/nearest_neighbor.py)

**Comment by alejoe91** [comment]
I'm a bit busy these days, but if you have time to make a PR to spiketoolkit too I'd be happy to review it!

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spikemetrics/pull/25
