### ISSUE TITLE
Error in isis_violations

### ISSUE THREAD

**Issue by MarineChap** [SpikeInterface/spikemetrics#26]
Hello, 
Is it a working package ? 

I tried to work with it but when running calculate_metrics method, there is an error due to a zero division. 
I tracked it down in the code and I am really surprised. 
Is that me or the method `calculate_isi_violations` is not called correctly ? 

```
def calculate_isi_violations(spike_times, spike_clusters, total_units, isi_threshold, min_isi, duration,
                             spike_cluster_subset=None, verbose=True)
```

is called in `calculate_metrics` like this : 
```
isi_viol = calculate_isi_violations(spike_times[in_epoch], spike_clusters[in_epoch], total_units,
                                            duration, params['isi_threshold'], params['min_isi'], verbose=verbose)
```
And indeed when I replace  my min_isi param value by my duration value, it is running (not what I want of course but running)

Thanks. 
Have a good evening, 
Marine

Full error message:
```
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-7-3a82a633ca85> in <module>
      7                       params=params,
      8                       duration=np.max(spike_times) -  np.min(spike_times),
----> 9                       channel_locations = channel_map,
     10                       )
     11 

/opt/conda/envs/fklab/lib/python3.7/site-packages/spikemetrics/metrics.py in calculate_metrics(spike_times, spike_clusters, amplitudes, pc_features, pc_feature_ind, params, duration, channel_locations, cluster_ids, epochs, seed, verbose)
     73         print("Calculating isi violations")
     74         isi_viol = calculate_isi_violations(spike_times[in_epoch], spike_clusters[in_epoch], total_units,
---> 75                                             duration, params['isi_threshold'], params['min_isi'], verbose=verbose)
     76 
     77         print("Calculating presence ratio")

/opt/conda/envs/fklab/lib/python3.7/site-packages/spikemetrics/metrics.py in calculate_isi_violations(spike_times, spike_clusters, total_units, isi_threshold, min_isi, duration, spike_cluster_subset, verbose)
    172                                                                 duration=duration,
    173                                                                 isi_threshold=isi_threshold,
--> 174                                                                 min_isi=min_isi)
    175 
    176     return viol_rates

/opt/conda/envs/fklab/lib/python3.7/site-packages/spikemetrics/metrics.py in isi_violations(spike_train, duration, isi_threshold, min_isi)
    593     num_violations = sum(isis < isi_threshold)
    594     violation_time = 2 * num_spikes * (isi_threshold - min_isi)
--> 595     total_rate = firing_rate(spike_train, duration)
    596     violation_rate = num_violations / violation_time
    597     fpRate = violation_rate / total_rate

/opt/conda/envs/fklab/lib/python3.7/site-packages/spikemetrics/metrics.py in firing_rate(spike_train, duration)
    637 
    638     """
--> 639     fr = spike_train.size / duration
    640 
    641     return fr

ZeroDivisionError: float division by zero
```

**Comment by alejoe91** [comment]
@colehurwitz can you take a look at this? Thanks for reporting it @MarineChap

**Comment by alejoe91** [comment]
@MarineChap you are absolutely right! Yes it is a working package and it'sused by `spiketoolkit`. However in spiketoolkit we call each function separately with kwargs.

**Comment by MarineChap** [comment]
Ah I understand better. So, before I closed this, you are advising we are using it thought spiketoolkit instead of this compute_metrics methods ?

**Comment by MarineChap** [comment]
When running your fix, I still have a problem when you give in input the pc_features in calculate_pc_metrics or calculate_drift_metrics. However, I am not sure if it is coming from me or not. 
`pc_features[in_epoch, :, :]`  gives this errors :
`too many indices for array: array is 3-dimensional, but 4 were indexed.`

I added a flatten() to fix the problem : 

`in_epoch = np.logical_and(spike_times >= epoch.start_time, spike_times < epoch.end_time).flatten()`

**Comment by alejoe91** [comment]
Thanks @MarineChap 

I'll refer to @jsiegle who is the main dev of the repo. Your solution looks right to me! Probably there's an extra 1 dimension popping up somewhere. Could you make a PR with a fix? Thanks!

**Comment by alejoe91** [comment]
> Ah I understand better. So, before I closed this, you are advising we are using it thought spiketoolkit instead of this compute_metrics methods ?

Yes I advice to use spiketoolkit as IMO it's a better wrapper to the functions. It allows to manupilate better the extractor objects and it saves the metrics as properties of the units ;)
