### ISSUE TITLE
Create package on pypi and/or conda-forge?

### ISSUE THREAD

**Issue by jaib1** [SpikeInterface/spikemetrics#4]
Hi guys,

I was talking to Josh Siegle about this: it would be nice if this repo was added as a package to
pypi and/or conda-forge (or any other Python package repository) so it could be installed easily as a standalone package. For the IBL, https://github.com/int-brain-lab/ibllib, we were thinking of using it, and it would be nice to have it as an easy dependency that we could specify in an environment yaml file, for example.

**Comment by alejoe91** [comment]
@jaib1 the repo is on pypi already.
Also we plane to release the spikeinterface repo as well. We are finishing up a few things to release a stable 1.0 version on pypi. You can find the docs here: https://spikeinterface.readthedocs.io/en/latest/

**Comment by alejoe91** [comment]
https://pypi.org/project/spikemetrics/

**Comment by jaib1** [comment]
oh great thanks! I will close this then.
